// Problem 2
// Even Fibonacci numbers
/* Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

// Fibonacci function
function fib(n) {
   if (n < 1) {
       return 1;
   }

   return fib(n-1) + fib(n-2);
}

var results = [];

var num = 1;
while (fib(num) < 4e6) {
   results.push(fib(num));
   num++;
}

// function to find the sum of the even numbers in the list
function even_sum(list) {
   var sum = 0;
   for (var i = 0; i < list.length; i++) {
       if (list[i] % 2 == 0) {
           sum += list[i];
       }
   }
   return sum;
}

// NOTE: Debug Code
// console.log(results);

// Store the sum in a variable and log it to console
sum = even_sum(results);
console.log(sum);
